version: "3.1"

services:
  broker:
    image: confluentinc/confluent-local:7.4.0
    hostname: broker
    container_name: broker
    ports:
      - "9092:9092"
      - "9101:9101"
    healthcheck:
      test: nc -z localhost 9092 || exit -1
      interval: 5s
      timeout: 10s
      retries: 100
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: "CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT"
      KAFKA_ADVERTISED_LISTENERS: "PLAINTEXT://broker:29092,PLAINTEXT_HOST://localhost:9092"
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_JMX_PORT: 9101
      KAFKA_JMX_HOSTNAME: localhost
      KAFKA_PROCESS_ROLES: "broker,controller"
      KAFKA_CONTROLLER_QUORUM_VOTERS: "1@broker:29093"
      KAFKA_LISTENERS: "PLAINTEXT://broker:29092,CONTROLLER://broker:29093,PLAINTEXT_HOST://0.0.0.0:9092"
      KAFKA_INTER_BROKER_LISTENER_NAME: "PLAINTEXT"
      KAFKA_CONTROLLER_LISTENER_NAMES: "CONTROLLER"
      KAFKA_LOG_DIRS: "/tmp/kraft-combined-logs"
      KAFKA_LOG4J_LOGGERS: org.apache.kafka.image.loader.MetadataLoader=WARN

  db:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: 123

  iot-gateway:
    build:
      context: ./iot-gateway
      dockerfile: Dockerfile
    container_name: iot-gateway
    environment:
      - PORT=3001
    ports:
      - "3001:3001"
    depends_on:
      - db
      - broker
    volumes:
      - .iot-gateway/src:/app/src

  temperature-monitor:
    build:
      context: ./temperature-monitor
      dockerfile: Dockerfile
    container_name: temperature-monitor
    environment:
      - PORT=3002
    ports:
      - "3002:3002"
    depends_on:
      - iot-gateway
    volumes:
      - .temperature-monitor/src:/app/src

  database-writer:
    build:
      context: ./database-writer
      dockerfile: Dockerfile
    container_name: database-writer
    environment:
      - PORT=3003
    ports:
      - "3003:3003"
    depends_on:
      - iot-gateway
    volumes:
      - .database-writer/src:/app/src

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
